export { CategoriaInterface } from './categoria.interface';
export { ServicioInterface } from './servicio.interface';
export { TarjetaCreditoInterface } from './tarjeta-credito.interface';
export { AsociadoInterface } from './asociado.interface';
export { PaqueteInterface } from './paquete.interface';
export { UbicacionInterface } from './ubicacion.interface';
export { ClienteInterface } from './cliente.interface';
export { PaqueteActivoInterface } from './paquete-activo.interface';
export { SesionInterface } from './sesion.interface';
export {ISocialProvider} from './socialProvider.interface';
